exclude: ^(vendor/|bin/|node_modules/|.editorconfig)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|json|yaml|yml|md)$

  - repo: https://github.com/lietu/go-pre-commit
    rev: v0.1.0
    hooks:
      #- id: errcheck
      - id: go-fmt-goimports
      # - id: go-test  TODO currently no tests
      #- id: go-vet
      # files: '^(cli/|lib/).*\.(go)$'
      - id: gofumpt
      #- id: golint
      #- id: staticcheck
      - id: go-mod-tidy
        files: "go.mod"
      #- id: golangci-lint
      #  files: "^(/cli|lib)"
