exclude: ^(vendor/|bin/|node_modules/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/lietu/go-pre-commit
    rev: v1.0.0
    hooks:
      - id: go-fmt-goimports
      - id: go-test
      - id: go-vet
      - id: gofumpt
      - id: golint
      - id: staticcheck
      - id: golangci-lint
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx prettier --write --ignore-unknown
        language: system
        types: [text]
        files: \.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml|html)$
