exclude: ^(vendor/|bin/|node_modules/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/lietu/go-pre-commit
    rev: v1.0.0
    hooks:
      - id: go-fmt-goimports
      - id: gofumpt
      - id: golint
      - id: staticcheck
  - repo: local
    hooks:
      - id: go-test-lib
        name: go-test (lib)
        entry: go test -race ./lib/...
        language: system
        pass_filenames: false
        files: ^lib/.*\.go$
      - id: go-vet-lib
        name: go-vet (lib)
        entry: go vet ./lib/...
        language: system
        pass_filenames: false
        files: ^lib/.*\.go$
      - id: go-test-app
        name: go-test (app)
        entry: go test ./app/...
        language: system
        pass_filenames: false
        files: ^app/.*\.go$
      - id: go-vet-app
        name: go-vet (app)
        entry: go vet ./app/...
        language: system
        pass_filenames: false
        files: ^app/.*\.go$
      - id: prettier
        name: Prettier
        entry: bunx prettier --write --ignore-unknown
        language: system
