project_name: usb-tree

version: 2

before:
  hooks:
    # Regenerate Wails bindings and embed assets
    - wails generate

builds:
  - id: linux-amd64
    main: .
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
    tags: [desktop, production]
    ldflags:
      - -s -w
    hooks:
      pre:
        - sh -c 'if [ -d "./third_party/libusb/linux/x86_64/pkgconfig" ]; then export PKG_CONFIG_PATH=./third_party/libusb/linux/x86_64/pkgconfig; fi'

  - id: windows-amd64
    main: .
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
    tags: [desktop, production]
    ldflags:
      - -s -w -H windowsgui
    flags:
      - -buildmode=exe

archives:
  - id: linux-tar
    ids: [linux-amd64]
    formats: ["tar.gz"]

  - id: windows-zip
    ids: [windows-amd64]
    formats: ["zip"]

changelog:
  use: github
