project_name: usb-tree

version: 2

before:
  hooks:
    # Build the frontend using Bun instead of npm
    - bash -c "cd frontend && bun install"
    - bash -c "cd frontend && bun run build"
    # Regenerate Wails bindings and embed assets
    - wails generate

builds:
  - id: linux-amd64
    main: .
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - PKG_CONFIG_PATH=./third_party/libusb/linux/x86_64/pkgconfig
    tags: [desktop, production]
    ldflags:
      - -s -w

  - id: windows-amd64
    main: .
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_CFLAGS=-I./third_party/libusb/windows/amd64/include
      - CGO_LDFLAGS=-L./third_party/libusb/windows/amd64/lib -lusb-1.0
    tags: [desktop, production]
    ldflags:
      - -s -w -H windowsgui

archives:
  - id: linux-tar
    ids: [linux-amd64]
    formats: ["tar.gz"]
    files:
      - LICENSE
      - README.md

  - id: windows-zip
    ids: [windows-amd64]
    formats: ["zip"]
    files:
      - LICENSE
      - README.md
      - ./third_party/libusb/windows/amd64/bin/libusb-1.0.dll

changelog:
  use: github
