// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitFrontend() {
  return window["go"]["main"]["App"]["InitFrontend"]()
}

export function Refresh() {
  return window["go"]["main"]["App"]["Refresh"]()
}
