name: Validate Pull Request and auto-fix some issues

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, edited]
  workflow_dispatch:

jobs:
  Validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libusb-1.0-0-dev libudev-dev pkg-config
          version: 1.0

      - name: Install repository JavaScript dependencies
        run: bun install --frozen-lockfile

      - name: Prepare Wails frontend assets
        working-directory: app/frontend
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: go-tools-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-tools-${{ runner.os }}-

      - name: Install tools
        run: |
          pip install pre-commit
          go install mvdan.cc/gofumpt@latest
          go install github.com/lietu/go-pre-commit@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: always()
